In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
import string

In [3]:
a=np.array(list(string.ascii_uppercase))

In [4]:
a

array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z'],
      dtype='<U1')

In [5]:
df=pd.DataFrame({"A":[1,2,3],"B":[4,5,6]})

In [6]:
df

A  B
0  1  4
1  2  5
2  3  6

In [7]:
df1=pd.Series([7,8,9])

In [8]:
df['C']=df1

In [9]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9

In [10]:
row={"A":4,"B":5,"C":6}

In [11]:
df=df.append(row,ignore_index=True)

<ipython-input-11-0ba4802b7779>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df=df.append(row,ignore_index=True)


In [12]:
df

A  B  C
0  1  4  7
1  2  5  8
2  3  6  9
3  4  5  6

In [13]:
df.drop([2])

A  B  C
0  1  4  7
1  2  5  8
3  4  5  6

In [14]:
df.drop("B",axis=1)

A  C
0  1  7
1  2  8
2  3  9
3  4  6

In [15]:
df.rename(columns={"C":"D"})

A  B  D
0  1  4  7
1  2  5  8
2  3  6  9
3  4  5  6

In [18]:
df=pd.read_csv("iris.csv")

In [19]:
df

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [20]:
x=df.iloc[:,[0,1,2,3]]
x

sepal.length  sepal.width  petal.length  petal.width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [21]:
y=df.iloc[:,4]
y

0         Setosa
1         Setosa
2         Setosa
3         Setosa
4         Setosa
         ...    
145    Virginica
146    Virginica
147    Virginica
148    Virginica
149    Virginica
Name: variety, Length: 150, dtype: object

In [22]:
from sklearn.preprocessing import LabelEncoder
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
x_train,y_train,x_test,y_test=train_test_split(x,y,test_size=0.2)


In [25]:
x_train.size

480

In [26]:
x_test.size

120

In [28]:
y_train.size

120

In [29]:
y_test.size

30

In [30]:
df["variety"].value_counts()

Setosa        50
Versicolor    50
Virginica     50
Name: variety, dtype: int64

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)


In [33]:
classifier_knn.fit(x_train,y_train)


ValueError: ignored

In [34]:
x_train.shape

(120, 4)

In [35]:
y_train.shape

(30, 4)

In [36]:
y_train=y_train.reshape(-1,1)

AttributeError: ignored

In [37]:
from sklearn.model_selection import train_test_split

In [38]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)


In [39]:
x_train.size

480

In [40]:
y_train.size

120

In [41]:
x_test.size

120

In [42]:
y_test.size

30

In [43]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn=KNeighborsClassifier(n_neighbors=5,metric="minkowski",p=2)
classifier_knn.fit(x_train,y_train)


KNeighborsClassifier()

In [44]:
y_pred=classifier_knn.predict(x_test)


In [45]:
y_pred

array([1, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0,
       2, 1, 1, 0, 1, 2, 2, 1])

In [46]:
y_pred.sort()

In [47]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [48]:
y_test

array([1, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0,
       2, 1, 1, 0, 1, 1, 1, 1])

In [49]:
y_test.sort()

In [50]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2])

In [52]:
from sklearn.metrics import confusion_matrix

In [54]:
confusion_matrix(y_pred,y_test)

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  2,  7]])

In [55]:
confusion_matrix(y_test,y_pred)


array([[10,  0,  0],
       [ 0, 11,  2],
       [ 0,  0,  7]])

In [56]:
classifier_knn.score(x_test,y_test)


0.23333333333333334

In [57]:
from sklearn.metrics import accuracy_score


In [58]:
accuracy_score(y_pred,y_test)


0.9333333333333333

In [59]:
from sklearn.linear_model import LogisticRegression


In [60]:
logmodel=LogisticRegression()


In [61]:
logmodel.fit(x_train,y_train)


LogisticRegression()

In [62]:
y_pred=logmodel.predict(x_test)


In [63]:
y_pred

array([1, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0,
       2, 1, 1, 0, 1, 2, 2, 1])

In [64]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2])

In [65]:
from sklearn.metrics import confusion_matrix


In [66]:
confusion_matrix(y_test,y_pred)


array([[2, 4, 4],
       [7, 3, 3],
       [1, 4, 2]])

In [67]:
logmodel.score(x_test,y_test)


0.23333333333333334

In [68]:
from sklearn.metrics import accuracy_score


In [69]:
accuracy_score(y_pred,y_test)


0.23333333333333334

In [70]:
from sklearn.naive_bayes import GaussianNB


In [71]:
classifier_nb=GaussianNB()


In [72]:
classifier_nb.fit(x_train,y_train)


GaussianNB()

In [73]:
GaussianNB(priors=None)


GaussianNB()

In [74]:
y_pred=classifier_nb.predict(x_test)
y_pred

array([1, 2, 1, 1, 2, 0, 1, 2, 0, 2, 0, 0, 0, 1, 1, 0, 0, 1, 2, 0, 2, 0,
       2, 1, 1, 0, 1, 2, 2, 1])

In [75]:
y_test

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2])

In [76]:
from sklearn.metrics import confusion_matrix


In [77]:
confusion_matrix(y_test,y_pred)


array([[2, 4, 4],
       [7, 3, 3],
       [1, 4, 2]])

In [78]:
classifier_nb.score(x_test,y_test)


0.23333333333333334