In [ ]:
import numpy as np
import pandas as pd

In [ ]:
arra_list=[1,2,3,4,5]
arra_list

[1, 2, 3, 4, 5]

In [ ]:
array=np.array(arra_list)

In [ ]:
print(array)

[1 2 3 4 5]


In [ ]:
print(np.max(array))

5


In [ ]:
print(np.min(array))

1


In [ ]:
dis={'Name':['pushpa','mehak','tanzima','nishu','prisha'],'Age':[23,21,21,13,16],'city':['botad','panjab','ahemdabad','gujrat','tamil']}
df=pd.DataFrame(dis)
print(df)

      Name  Age       city
0   pushpa   23      botad
1    mehak   21     panjab
2  tanzima   21  ahemdabad
3    nishu   13     gujrat
4   prisha   16      tamil


In [ ]:
df=df.drop('city', axis=1)
df

Name  Age
0   pushpa   23
1    mehak   21
2  tanzima   21
3    nishu   13
4   prisha   16

In [ ]:
data=pd.read_csv('/content/fracture.csv')
data

id        age sex     fracture  weight_kg  height_cm      medication  \
0      469  57.052768   F  no fracture       64.0      155.5  Anticonvulsant   
1     8724  75.741225   F  no fracture       78.0      162.0   No medication   
2     6736  70.778900   M  no fracture       73.0      170.5   No medication   
3    24180  78.247175   F  no fracture       60.0      148.0   No medication   
4    17072  54.191877   M  no fracture       55.0      161.0   No medication   
..     ...        ...  ..          ...        ...        ...             ...   
164  21892  77.982543   M     fracture       74.0      164.0   No medication   
165  24140  50.285303   F     fracture       59.0      161.0   No medication   
166   6969  46.359721   M     fracture       67.0      169.0   No medication   
167   5505  54.788368   M     fracture       70.0      166.0   No medication   
168     71  69.994822   F     fracture       68.5      165.0   No medication   

     waiting_time     bmd  
0              18  0.8793  
1              56  0.7946  
2              10  0.9067  
3              14  0.7112  
4              20  0.7909  
..            ...     ...  
164            49  0.7941  
165             6  0.7971  
166            10  0.8037  
167            14  0.8072  
168            25  0.8664  

[169 rows x 9 columns]

In [ ]:
data.head(15)
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   id            169 non-null    int64  
 1   age           169 non-null    float64
 2   sex           169 non-null    object 
 3   fracture      169 non-null    object 
 4   weight_kg     169 non-null    float64
 5   height_cm     169 non-null    float64
 6   medication    169 non-null    object 
 7   waiting_time  169 non-null    int64  
 8   bmd           169 non-null    float64
dtypes: float64(4), int64(2), object(3)
memory usage: 12.0+ KB


In [ ]:
x=data.iloc[:,0:4].values
y=data.iloc[:,4].values



In [ ]:
from sklearn.preprocessing import LabelEncoder
labelEncoder_y=LabelEncoder()

y=labelEncoder_y.fit_transform(y)
y


array([23, 40, 35, 19, 14, 25, 39, 18, 23, 34, 21, 29, 38, 48, 32, 38, 27,
       26, 34, 10, 18, 35, 36, 14, 37, 28, 29, 31, 14, 31, 31, 18, 51,  6,
       26, 42, 32, 40, 42, 40, 12, 33, 19, 41, 15, 36, 10, 15, 45, 47, 37,
        2, 29, 17, 41, 46, 27, 29, 34, 13, 22, 19, 21, 18, 15,  7, 29, 31,
       13, 32, 37, 21, 37, 44, 35, 18, 33, 14, 31, 11, 21, 49, 38, 32, 15,
       43, 38, 27, 22, 41, 39, 14, 40, 29, 40, 33, 43, 50, 36, 16, 20, 33,
       19, 39, 26,  8, 10, 32, 27, 21,  9, 18, 35, 11, 36, 24, 23, 19, 21,
       12, 13, 31, 15, 13, 16, 20, 10,  3, 41,  1,  8,  0,  8, 12, 41, 10,
       17, 12, 46, 22, 18,  8, 11, 26, 16, 21, 35, 15,  4, 26,  8, 13, 21,
       14, 20, 14, 23, 29, 14,  5, 12, 23, 19, 42, 36, 18, 27, 32, 30])

In [ ]:
from sklearn.model_selection import train_test_split


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [ ]:
x_train

array([[21892, 77.98254308, 'M', 'fracture'],
       [2179, 53.3954402, 'M', 'no fracture'],
       [2797, 84.72176364, 'M', 'fracture'],
       [23919, 53.7692897, 'F', 'fracture'],
       [2143, 44.23967859, 'M', 'no fracture'],
       [8999, 60.23658177, 'F', 'no fracture'],
       [17182, 79.39970672, 'M', 'no fracture'],
       [224, 76.94473691, 'F', 'fracture'],
       [5509, 76.8639147, 'M', 'no fracture'],
       [9051, 63.28728844, 'F', 'no fracture'],
       [398, 51.43071736, 'F', 'no fracture'],
       [334, 70.40792405, 'F', 'no fracture'],
       [2018, 86.85986938, 'M', 'fracture'],
       [17090, 52.79292063, 'M', 'no fracture'],
       [8850, 50.36051644, 'F', 'no fracture'],
       [5350, 53.53171717, 'M', 'fracture'],
       [8592, 68.06825266, 'F', 'no fracture'],
       [24204, 68.55087894, 'F', 'no fracture'],
       [23625, 59.70722073, 'M', 'no fracture'],
       [688, 77.15502036, 'M', 'no fracture'],
       [67, 76.74551614, 'F', 'fracture'],
       [8751, 63

In [ ]:
x_train.size

540

In [ ]:
y_train.size

135

In [ ]:
y_test.size
y_train

array([36, 32, 12,  3, 43, 32, 38,  1, 47, 21, 28, 41, 13, 39, 35, 31,  9,
       32, 40, 31, 12, 15, 40, 14, 10, 40, 15, 29, 10, 26, 16, 46, 33,  8,
       18, 16, 31,  8, 14,  6, 37, 22, 23, 14, 38, 11, 15, 17, 41, 32, 42,
       16, 29, 42, 38,  0, 35, 20, 11, 18, 10, 14, 33, 19, 44, 40, 15, 22,
       18, 14, 37, 22, 26,  2, 12, 27, 26, 35, 23, 32, 34, 27, 36, 13, 27,
       15, 26, 10,  4, 41, 29, 13, 29, 34, 45, 29, 36, 31, 43, 36, 27, 19,
       33, 35, 19, 19, 23, 21, 17, 38,  5, 48, 23, 39, 18, 34, 12, 51, 21,
       31, 36, 13,  7, 41, 46,  8, 11, 29, 20, 10, 41, 12, 19, 42, 26])

In [ ]:

from sklearn.linear_model import LogisticRegression

In [ ]:
logmodel=LogisticRegression()

In [ ]:
logmodel.fit(x_train,y_train)

ValueError: ignored

In [ ]:
y_pred=logmodel.predict(x_test)

NotFittedError: ignored

In [ ]:
y_pred

NameError: ignored