In [ ]:
#hstack
import numpy as np
a=np.array([[1,2,3,4],[5,8,9,6]])
b=np.array([[5,6,7],[40,34,22]])
a,b

(array([[1, 2, 3, 4],
        [5, 8, 9, 6]]), array([[ 5,  6,  7],
        [40, 34, 22]]))

In [ ]:
# arange
c=np.arange(1,11)
c


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
d=np.arange(13,131,13)
d

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [ ]:
d=np.arange(12,121,12)
d

array([ 12,  24,  36,  48,  60,  72,  84,  96, 108, 120])

In [ ]:
#linspace
c=np.linspace(1.0,5.0,num=10)
c



array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#indexing and slicing
h=np.array([(1,2,3),(4,5,6)])
h

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
h.shape

(2, 3)

In [ ]:
h.size

6

In [ ]:
h[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
h[0]

array([1, 2, 3])

In [ ]:
h[0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
h[0:1] #first row h[0]

array([[1, 2, 3]])

In [ ]:
h[1:2] #second row h[1]

array([[4, 5, 6]])

In [ ]:
#last column
h[0:,2]

array([3, 6])

In [ ]:
h[1:,2] #last element

array([6])

In [ ]:
#first 
h[:,0]

array([1, 4])

In [ ]:
o=np.ones((4,4))
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
o=np.ones((4,4))
o


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr=np.random.normal(0.4.size=(3,2))
arr

SyntaxError: ignored

In [ ]:
import numpy as np
arr=np.random.randint(0,10,size=(3,2))
print(arr)

[[2 2]
 [3 0]
 [6 2]]


In [ ]:

arr=np.random.randint(0,10,size=(3,3))
print(arr)
print(arr.min())
print(arr.max())

[[9 4 7]
 [0 5 1]
 [9 5 7]]
0
9


In [ ]:
arr=np.array([1,2,3,4,5])
arr +=5
print(arr)

[ 6  7  8  9 10]


In [ ]:
arr=np.random.randint(0,10,size=(3,3))
print(arr)
print(arr.shape)
print('After Reshape')
arr=arr.reshape(9,1)
print(arr)

[[6 8 0]
 [3 3 9]
 [8 6 1]]
(3, 3)
After Reshape
[[6]
 [8]
 [0]
 [3]
 [3]
 [9]
 [8]
 [6]
 [1]]


In [ ]:
ab=np.array([[1,2,4],[5,6,7]])
ab

array([[1, 2, 4],
       [5, 6, 7]])

In [ ]:
bc=np.array([[7,8,9],[22,11,12]])
bc

array([[ 7,  8,  9],
       [22, 11, 12]])

In [ ]:
abc=np.add(ab,bc)
abc

array([[ 8, 10, 13],
       [27, 17, 19]])

In [ ]:
ay=np.zeros((5,2))
ay

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
ax=np.ones((3,3))
ax


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
student={'tanzim':78,'mehak':77,'pushpa':65,'kajal':78,'krisha':69}
print(student)

{'tanzim': 78, 'mehak': 77, 'pushpa': 65, 'kajal': 78, 'krisha': 69}


In [ ]:
type(student)

dict

In [ ]:
import pandas as pd

In [ ]:
name=['raj','mehak','tanzima','pushpa']
name

['raj', 'mehak', 'tanzima', 'pushpa']

In [ ]:
mark=[67,77,90,88]
mark

[67, 77, 90, 88]

In [ ]:
type(mark)

list

In [ ]:
df=pd.Series(data=mark)
df

0    67
1    77
2    90
3    88
dtype: int64

In [ ]:
df=pd.Series(data=name)
df


0        raj
1      mehak
2    tanzima
3     pushpa
dtype: object

In [ ]:
type(df)

pandas.core.series.Series

In [ ]:
student={'name':name,'mark':mark}
student

{'name': ['raj', 'mehak', 'tanzima', 'pushpa'], 'mark': [67, 77, 90, 88]}

In [ ]:
df=pd.DataFrame(data=student)
df

name  mark
0      raj    67
1    mehak    77
2  tanzima    90
3   pushpa    88

In [ ]:
df.shape

(4, 2)

In [ ]:
df.info

<bound method DataFrame.info of       name  mark
0      raj    67
1    mehak    77
2  tanzima    90
3   pushpa    88>

In [ ]:
df.describe

<bound method NDFrame.describe of       name  mark
0      raj    67
1    mehak    77
2  tanzima    90
3   pushpa    88>

In [ ]:
df.head(2)

name  mark
0    raj    67
1  mehak    77

In [ ]:
df.tail(2)

name  mark
2  tanzima    90
3   pushpa    88

In [ ]:
df=pd.read_csv('/content/student.csv')
df

Name      Age        marks
0    Raj       20          77
1    Pushpa    23          97
2    Tanzima   21          98
3    Ami       21          89
4    Mehak     22          98
5    Kajal     20          67
6    Krisha    20          67
7    Falguni   21          87
8    Antima    23          67
9    Manali    20          69
10   Jigar     25          90
11   Asad      21          89
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head

<bound method NDFrame.head of    Name      Age        marks
0    Raj       20          77
1    Pushpa    23          97
2    Tanzima   21          98
3    Ami       21          89
4    Mehak     22          98
5    Kajal     20          67
6    Krisha    20          67
7    Falguni   21          87
8    Antima    23          67
9    Manali    20          69
10   Jigar     25          90
11   Asad      21          89
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77>

In [ ]:
df

Name      Age        marks
0    Raj       20          77
1    Pushpa    23          97
2    Tanzima   21          98
3    Ami       21          89
4    Mehak     22          98
5    Kajal     20          67
6    Krisha    20          67
7    Falguni   21          87
8    Antima    23          67
9    Manali    20          69
10   Jigar     25          90
11   Asad      21          89
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77

In [ ]:
df.shape

(19, 1)

In [ ]:
df.info

<bound method DataFrame.info of    Name      Age        marks
0    Raj       20          77
1    Pushpa    23          97
2    Tanzima   21          98
3    Ami       21          89
4    Mehak     22          98
5    Kajal     20          67
6    Krisha    20          67
7    Falguni   21          87
8    Antima    23          67
9    Manali    20          69
10   Jigar     25          90
11   Asad      21          89
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77>

In [ ]:
df.tail(6)

Name      Age        marks
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77

In [ ]:
df.head(6)

Name      Age        marks
0   Raj       20          77
1   Pushpa    23          97
2   Tanzima   21          98
3   Ami       21          89
4   Mehak     22          98
5   Kajal     20          67

In [ ]:
df.columns


Index(['Name      Age        marks'], dtype='object')

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.info

<bound method DataFrame.info of    Name      Age        marks
0    Raj       20          77
1    Pushpa    23          97
2    Tanzima   21          98
3    Ami       21          89
4    Mehak     22          98
5    Kajal     20          67
6    Krisha    20          67
7    Falguni   21          87
8    Antima    23          67
9    Manali    20          69
10   Jigar     25          90
11   Asad      21          89
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77>

# New Section

In [ ]:
df.describe

<bound method NDFrame.describe of    Name      Age        marks
0    Raj       20          77
1    Pushpa    23          97
2    Tanzima   21          98
3    Ami       21          89
4    Mehak     22          98
5    Kajal     20          67
6    Krisha    20          67
7    Falguni   21          87
8    Antima    23          67
9    Manali    20          69
10   Jigar     25          90
11   Asad      21          89
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77>

In [ ]:
df.iloc[2]

Name      Age        marks    Tanzima   21          98
Name: 2, dtype: object

In [ ]:
df.iloc[12:19]

Name      Age        marks
12   Rinal     22          76
13   Nikunj    23          99
14   Hiral     22          74
15   Mitesh    24          66
16   Alkesh    24          83
17   Jay       23          81
18   Saloni    23          77

In [ ]:
df.columns

Index(['Name      Age        marks'], dtype='object')