In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/iris.csv')

In [ ]:
data

sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [ ]:
data.head(5)

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [ ]:
data.tail(5)

sepal.length  sepal.width  petal.length  petal.width    variety
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal.length  150 non-null    float64
 1   sepal.width   150 non-null    float64
 2   petal.length  150 non-null    float64
 3   petal.width   150 non-null    float64
 4   variety       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
data.size

750

In [ ]:
data.shape

(150, 5)

In [ ]:
x=data.iloc[:,0:4].values
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [ ]:
y=data.iloc[0:,4].values

In [ ]:
y

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolor', 'Versicolor', 'Versicolor', 'Versicolor',
       'Versicolo

In [ ]:
y.shape

(150,)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
labelencoder_y=LabelEncoder()

In [ ]:
labelencoder_y

LabelEncoder()

In [ ]:
y=labelencoder_y.fit_transform(y)

In [ ]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
from sklearn.svm import SVC

In [ ]:
svc=SVC(kernel='sigmoid')

In [ ]:
svc

SVC(kernel='sigmoid')

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.5)

In [ ]:
svc.fit(x_train,y_train)

SVC(kernel='sigmoid')

In [ ]:
y_pred=svc.predict(x_test)

In [ ]:
y_pred

array(['Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa', 'Setosa',
       'Setosa', 'Setosa', 'Setosa'], dtype=object)

In [ ]:
y_test

array(['Versicolor', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Versicolor', 'Virginica',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Versicolor', 'Versicolor', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Setosa', 'Virginica',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Virginica',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Virginica',
       'Setosa', 'Setosa', 'Versicolor', 'Virginica', 'Versicolor',
       'Setosa', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Virgin

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[21,  0,  0],
       [27,  0,  0],
       [27,  0,  0]])

In [ ]:
(21/50)*100

42.0

In [ ]:
(38*2)/100

0.76

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
logmodel=LogisticRegression()

In [ ]:
logmodel

LogisticRegression()

In [ ]:
logmodel.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_pred=logmodel.predict(x_test)

In [ ]:
y_pred

array(['Versicolor', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Versicolor', 'Virginica',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Versicolor', 'Versicolor', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Virginica',
       'Setosa', 'Setosa', 'Versicolor', 'Virginica', 'Virginica',
       'Setosa', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Virgi

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[21,  0,  0],
       [ 0, 26,  1],
       [ 0,  2, 25]])

In [ ]:
(107*20)/100

21.4

In [ ]:
logmodel.score(x_test,y_test)

0.96

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
classifier_knn=KNeighborsClassifier(n_neighbors=5, metric='minkowski', p=2)

In [ ]:
classifier_knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
y_pred=classifier_knn.predict(x_test)

In [ ]:
y_pred

array(['Versicolor', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Versicolor', 'Virginica',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Versicolor', 'Versicolor', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Setosa', 'Virginica',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Virginica',
       'Setosa', 'Setosa', 'Versicolor', 'Virginica', 'Versicolor',
       'Setosa', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Virgi

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test,y_pred)

array([[21,  0,  0],
       [ 0, 27,  0],
       [ 0,  1, 26]])

In [ ]:
# NaiveBias Model

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
classifier_nb=GaussianNB()

In [ ]:
classifier_nb.fit(x_train,y_train)

GaussianNB()

In [ ]:
y_pred=classifier_nb.predict(x_test)

In [ ]:
y_pred

array(['Versicolor', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Versicolor', 'Virginica',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Versicolor', 'Versicolor', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Versicolor',
       'Setosa', 'Setosa', 'Versicolor', 'Virginica', 'Virginica',
       'Setosa', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Virg

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_pred,y_test)

0.9466666666666667

In [ ]:
classifier_nb.score(x_test,y_test)

0.9466666666666667

In [ ]:
# Creating Decision Tree Classifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
cld=DecisionTreeClassifier()

In [ ]:
cld.fit(x_train,y_train)

DecisionTreeClassifier()

In [ ]:
y_pred=cld.predict(x_test)

In [ ]:
y_pred

array(['Versicolor', 'Versicolor', 'Versicolor', 'Versicolor', 'Setosa',
       'Virginica', 'Setosa', 'Virginica', 'Setosa', 'Versicolor',
       'Versicolor', 'Virginica', 'Setosa', 'Virginica', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Virginica',
       'Setosa', 'Virginica', 'Virginica', 'Versicolor', 'Virginica',
       'Virginica', 'Setosa', 'Setosa', 'Virginica', 'Setosa',
       'Virginica', 'Virginica', 'Versicolor', 'Versicolor', 'Versicolor',
       'Virginica', 'Virginica', 'Versicolor', 'Setosa', 'Versicolor',
       'Setosa', 'Versicolor', 'Virginica', 'Versicolor', 'Setosa',
       'Setosa', 'Setosa', 'Setosa', 'Virginica', 'Versicolor',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Setosa',
       'Virginica', 'Versicolor', 'Versicolor', 'Virginica', 'Versicolor',
       'Setosa', 'Setosa', 'Versicolor', 'Virginica', 'Virginica',
       'Setosa', 'Virginica', 'Versicolor', 'Versicolor', 'Setosa',
       'Versicolor', 'Virg